* Joke
** 经典搞笑：一个BUG引发的血案|为程序员打造的年终大片
<2012-10-06 周六>
数百条线程为何频繁断开，
回调函数为何迟迟没有结果，
mysql的数据为何屡遭黑手，
连环嵌 套循环案，究竟是何人所为？？
诡异的bug背后究竟是人是鬼，传来的对象次次为空的事件又 隐藏着什么？
这一切的背后，是类型转换的错误，还是空指针异常。
敬请关注今晚9点程序员 IT年度巨献《加班的不归路》？
让我们跟随着镜头走进程序员变态狂的内心世界… 
即将上映的年终大片：
《加班33天》
《那些年，我们一起做的项目》
《宕机惊魂7》
《通宵之 城4》
《程序员的救赎》
《哈利波特与编译原理》
《让需求飞2》
《考核来了4》
《翻滚吧！PM 》
《东写西读2011》
《喜羊羊与灰太狼之开心调程序》
《上线历险记》
《菜鸟崛起》
《杨门女 将之BUG堆积如山》

** 产品经理你伤不起
<2012-10-06 周六>
1. Dropbox提供储存功能，然后用户要求提供删除功能。提供之后，用户要求提供误删除恢
   复功能。提供之后，用户要求提供永久删除无法恢复功能。提供之后，用户要求提供永久
   删除紧急恢复功能。提供之后，dropbox创始人自杀，遗书上写着：I AM A SB.
2. Facebook入华，用户要求提供注销功能。提供之后，用户要求提供恢复帐号功能。提供之
   后，用户要求提供永久注销功能。提供之后，用户要求提供永久注销后反悔功能。提供之
   后，用户要求提供永久注销后不能反悔功能。Mark自杀，遗书是：你们TM的有准主意的时
   候吗？
3. iPhone5全面进入中国，用户要求提供四喇叭。乔布斯提供之后，用户要求有镜子。乔布
   斯提供之后，用户要求有收音机。乔布斯提供之后，用户要求有手写板。乔布斯提供之后，
   用户要求提供双卡双待。提供之后，用户要求预装动感地带。乔布斯吐血说：去华强北直
   接买山寨机会死啊？
4. Twitter获准入华，用户要求提供评论功能。提供之后，用户要求提供传图功能。提供之
   后，用户要求提供表情功能。提供之后，用户要求提供5000字符。提供之后，用户要求上
   传音频。提供之后，用户要求绑定美图秀秀。提供之后，用户破口大骂：XXX是谁说推特
   简洁的？
5. 一位腾讯的QQ产品经理崩溃了，发疯之前他根据用户需求依次做了以下功能：隐身，对其
   隐身，隐身对其可见，对其一三五隐身，对其21点后隐身，对其隐身可见签名，对其隐身
   可见最后一次在线签名，隐身对其可见但只显示最后一次在线签名，对其隐身群内自动屏
   蔽呈不在线状且他人不能提及。
** 一看到某些人签名写个“我们是糖，甜到哀伤”。我就想说一句“你们是蛋，扯到膀胱” 
[2012-10-06 周六 17:02]
** 昨晚店面被撬了，一店衣服没拿，就把我的一台电脑一条烟偷了，报案了，jc进来转了一圈，第一句话，你这件衣服怎么卖？
 [2012-10-06 周六 17:13]
** 三国野史--马伯庸

   - 操与马超战于潼关。西兵悍勇，纵骑攻之，操军不敌，遂大溃而走。操杂于乱
   军之中，马超策骑疾追，乃大呼：“长髯者，曹操也。”操闻之大惊，割须弃袍，以旗角掩
   面，方亡归本营。众来问安，操抚膝大哭：“倘使云长在侧，孤必不致此。”众将问曰：“
   关君侯武姿卓然，丞相颇思否？”操对曰：“吾思云长美髯也。

   - 明嘉靖朝间，兵部右侍郎范钦始建天一阁，置古善、孤本于其内，良加眷护，卷册至七万余。
   时有仆役举烛不慎，阁中走水。护院不得以，遽以水泼浇。火既熄，范钦点检古本，有《三国志》与《范文正公集》两下交叠，页濡粘连，字多互篡。
   范钦揭卷读之，见《诸葛亮传》上犹有洇迹。其上曰：“臣亮言：先帝创业未半而中道崩殂。越明年，政通人和，百废俱兴。

   - 魏延在蜀中，每随亮出,欲请兵万人,与亮异道会于潼关，而亮为万全策，不许
   。延志不得伸，心积愤懑。而又与杨仪交恶，深怨葛氏偏袒太甚。凡数年，腹部辄绞痛，发
   时汗如雨下，鞍马不扶。医者断曰：“将军情志所伤，忧思恼怒，而致横犯胃腑。此吞酸之
   症也。”延请其方，医者曰：“名姓或有碍。”
   魏延别传》云：“魏延，字馈阳，义阳人也。少时慷慨，于乡里乐善好施，多行义举
   ，曾放言曰：“但有寸金，必馈吾乡。”故表字“馈阳”。后，人谓不祥，遂改之。

** When I was a kid
   发信人: ifas (连个手机号都不值), 信区: Joke
   标  题: when i was a kid
   发信站: 水木社区 (Wed Dec  3 19:32:25 2008), 站内

   When I was a kid I used to pray every night for a new bicycle.
   Then I realised God doesn’t work that way, so I stole
   one and prayed for forgiveness.

   --

   ※ 来源:·水木社区 newsmth.net·[FROM: 219.236.122.*]
** 《强大的冰女》
   冰女他日出猴棒，打得幻刺直尿炕；
   冰女他日出希瓦，打得巨魔直犯傻；
   冰女闲来合双刀，虎妞打成小花猫；
   冰女堆钱买辉耀，烧的幽鬼嗷嗷叫；
   冰女撑血出臂章，幻刺红字也不慌；
   冰女吸血出撒旦，小狗见了也流汗；
   冰女祭品偷肉山，拍拍只能撕床单；

** 有一只猪400斤，一座桥承重200斤，猪怎么过桥？
   发信人: ccccc (嘴嘴·不是破嘴), 信区: Joke
   标  题: 有一只猪400斤，一座桥承重200斤，猪怎么过桥？
   发信站: 水木社区 (Sun Nov  9 19:07:22 2008), 站内

   问题：有一只猪四百斤，一座桥承重两百斤，猪怎么过桥？

   条件：

   1.猪是活猪，任何解决方案都不得切割猪

   2.故事发生在猪王国，不要引入人的因素

   3.是过桥，不是过河，不要说是游泳过去

   4.是过桥，不是过涧，不要说是飞过去丫

   5.桥是承重两百斤的桥，把桥挪到平地上抑或过另一座承重超过四百斤的桥都属改
   变性状

   6.不是文字游戏，不要说“猪晕过去了”

   ————————————————————

   以下是网友跟帖：

   作者：千年寺

   综合前面高人们的意见

   一：减肥，用什么减肥方法都可以，电视广告上多的是！此乃女猪所为！

   二：南辕北辙，环绕地球一圈，此乃强猪所为！

   三：化身沙僧二师哥！此乃神猪所为！

   四：桥有多长？练个跳远行不？此乃奥运跳远冠军猪所为！


   作者：健笑

   1、这头猪叫“朱坚强”

   2、这头猪叫“四百斤”

   3、这头猪是临产的母猪，产仔后剩200斤

   4、这头猪会轻功

   5、这头猪腿比桥长，直接跨过去的

   6、这头猪是“飞天猪”

   ……

   作者：GaAs

   猪硬着头皮走过去了~~！！~~~~！！

   猪硬着头皮走过去了~~！！~~~~！！

   猪硬着头皮走过去了~~！！~~~~！！

   猪硬着头皮走过去了~~！！~~~~！！

   5、这头猪腿比桥长，直接跨过去的


   大家一起开动脑筋，想想有啥好办法。。。牛人们，一起探讨下，攻克这个难关！

   利尿剂、泻药、高渗葡萄糖、脱水剂、抽脂
   不知道最后一项算不算变向切割

   其实不仅仅是腿长的猪可以直接跨过去……
   就算腿超级短，只要身子超级长的猪也可以过去，前两条腿都到对岸了，后两条腿还没上桥
   呢……

   如果桥允许净载荷是200斤的话，或许可以这样：
   猪做找一块比桥略长的木板，两头装上轮子，猪像玩滑板一样踩在中间，冲过去，
   任何时候只有两个轮子在桥上，所以桥只承重一半。

   #+BEGIN_EXAMPLE
   猪
   ____
   | \
   |  \
   |   \桥,倾角大于60度
   |    \
   |     \   对岸
   |      \________
   |      |
   |~~~~~~|
   |~~~~~~|
   河
   #+END_EXAMPLE

   只要桥的倾角达到90度,多重的猪都可以过去,不摔死就行

   脚踩两座桥，正好各承重200斤。

   猪也在想找个问题，哈哈哈

   酒是穿肠毒药，色是刮骨钢刀，财是惹祸根苗，气是雷烟火炮。

   这四句话，说的是酒色财气这几样东西，千万不要沾，沾上就得惹事，轻则伤身，
   重则害命。这不嘛，有一只猪，这天喝多了，歪歪扭扭往家里赶，迎面看见一座桥。他仔细
   这么一打量，这地儿以前没来过啊……心里就发迷糊。书中暗表，怎么回事儿啊？这猪它不
   是喝晕了嘛，两眼根本就看不清东西了，就低着头看着脚赶路，一不留神，走茬路了。

   这猪心想，没来过就没来过吧，怎么回不是回啊。就往桥上走，还没等上去呢，旁
   边过来一人：“嘿~~说你呐，站住！”就把这猪拉住了。这猪一瞧，怎么回事儿，我一没贪
   赃，二没枉法，三不算酒后驾驶，你没事儿不让我走路干嘛？仔细打量，来的这人，长得一
   般，穿得利落，是一套制服。怎么知道呢？上面明白印着一行字“看桥员”。

   看桥员用手一指，这猪顺着一望，瞧见这桥上刻着四个大字“限重一百斤”。“瞧
   见没，你……总有四五百斤上下了吧，你要上去，非把这桥压塌了不可。绕道吧，赶紧的，
   走走走。”就轰这猪。

   要不怎么说喝酒害人呢，要放往日，这猪也就绕道了，这又不是平常自己走的，绕
   回原道就完了。今儿这猪喝高了，被人一轰，还上来脾气了。噢，你让我绕我就绕，那哪儿
   行啊。瞧不起我，以为我胖，我就过不去了？今儿爷爷给你瞧个鲜儿。这猪伸手就把看桥员
   拨拉到一边去了，后退了几步，奔着桥就跑过去了，眼看到桥边上，这猪较一力丹田混元气
   ，舌尖一舔上牙塘，脚尖一点，脑袋一晃，ri的一声，跳在空中。旁边过路的可看傻了眼，
   哥哥大爷，嫂子弟妹，瞧见没有，空中飞人啊，哗~~~可热闹瞭。

   看热闹的暂且不说，再说这猪跳在空中，还那句话，喝酒害人，怎么呢？本来这只
   猪，是个练家子，出身可了不得，乃是水木社区粥客版的当家，跳过的大坑无数，轻功非常
   了得，区区一座小桥，扭扭腰就蹦过去了。今天不行，今天它喝酒了，脚软，跳起来眼看着
   还没到那一边就往下落，想起来了，噢，今天我喝多了，跳的时候劲儿没用够……那哪儿行
   啊，噢，我砸下去，把桥砸塌了，好说不好听，丢人就丢大了，不行。想到这儿，这猪咬咬
   牙，把压箱底的绝活拿出来了。

   只见它，左后蹄一踩右后蹄，“蹭”的一声，往前窜了五尺，右后蹄再一踩左后蹄
   ，“蹭”的一声，又窜了五尺……正好落在桥的那一头。

   这正是：
   猪头三抄水，轻过限重桥。


   ※ 来源:·水木社区 newsmth.net·[FROM: 123.169.79.*]
** 公园情侣谈情说爱被老太太骂
   公园有一对恋人正在甜蜜，女孩撒娇说老公：我牙痛！男孩于是吻了女孩一口问：还疼吗？
   女孩说：不痛了！一会女孩又撒娇的说：老公，我脖子痛！男孩又吻了吻女孩的脖子，又问
   这回还疼吗女孩很开心的说：不痛了！旁边一老太太站着看了半天了忍不住了,上前就问小
   伙子说：。。。。。小伙子你真神了，你能治痔疮不?
** 好久没笑趴下了
   明月几时有,自己抬头瞅

   你有什么不开心的事? 说出来让大家开心一下.

   女人是水做的,男人是泥做的,李俊基李宇春都是水泥做的。

   “你要是嫁人,不要嫁给别人,更不要嫁给我......”

   您真是贱人多忘事啊

   披着凉皮的狼
** 打击面太大
   A:周济这秃驴
   B:后两个字打击面太大了吧
** 改名
   话说某好友，原名张铁杵，10年后忽闻其改名曰：张针
** 嗬嗬,记起了某年某大期间的一件趣事
   标  题: Re: 嗬嗬，记起了某年某大期间的一件趣事
   发信站: 水木社区 (Tue Oct 16 11:08:44 2007), 站内

   在介绍拉萨市长罗布顿珠同志的时候，全场哄笑
   记者注意到常委里只有胡core一人表情严肃
   包括温等人都忍不住笑起来
   当然事后大家猜测是因为胡当年在西藏早就笑过了

** 我见到的最短的笑话
   发信人: clusterbang (cluster), 信区: Joke
   标  题: 我见到的最短的笑话
   发信站: 水木社区 (Sat Oct 13 19:47:00 2007), 站内

   长个包子样就别怨狗跟着！
   ------------------------------------------------
   发信人: chumsdock (微笑服务), 信区: Joke
   标  题: Re: 我见到的最短的笑话
   发信站: 水木社区 (Sat Oct 13 19:47:21 2007), 站内

   从前有个太监
   【 在 clusterbang (cluster) 的大作中提到: 】
   : 长个包子样就别怨狗跟着！
   -------------------------------------------------
   发信人: milicic (人肉生理学家), 信区: Joke
   标  题: Re: 我见到的最短的笑话
   发信站: 水木社区 (Sat Oct 13 19:51:01 2007), 站内

   下面呢？

   【 在 chumsdock (微笑服务) 的大作中提到: 】
   : 从前有个太监
   ---------------------------------------------------
   发信人: zgntc (攒钱买辆小四轮), 信区: Joke
   标  题: Re: 我见到的最短的笑话
   发信站: 水木社区 (Sat Oct 13 19:51:29 2007), 站内

   没了
   【 在 milicic (人肉生理学家) 的大作中提到: 】
   : 下面呢？

** QQ上聊天。
   　　偶：我的头像牛B吗？
   　　M...
** 到哪里
   某日，一位小姐打电话叫出租车。
   小姐："你好！我在某某路口，我要搭计程车。"
   司机："那你穿着什么衣服呢？"小姐："我穿白色上衣，蓝色裙子。"
   司机："到哪里？"
   小姐："到膝盖。"司机："。。。。。。"
** 验算
   考试中某学生拿出骰子，摇出十道选择题答案。快结束时他突然又拿出来摇。
   监考老师终于忍无可忍："你在干什么？"
   学生答："我在验算。"

** 小白兔
   发信人: k4kid (kay), 信区: Joke
   标  题: 我也来个小白兔的冷笑话
   发信站: 北邮人论坛 (Mon Jun 25 02:38:26 2007), 站内

   小白兔蹦蹦跳跳到小卖部，问：老板，你们有没有萝卜啊？
   老板：没有

   第二天，小白兔蹦蹦跳跳到小卖部，问：老板，你们有没有萝卜啊？
   老板：没有

   第三天，小白兔蹦蹦跳跳到小卖部，问：老板，你们有没有萝卜啊？
   老板：没有，你再来问我就把你的耳朵剪下来！

   第四天，小白兔蹦蹦跳跳到小卖部，问：老板，你们有没有剪刀啊？
   老板：没有
   小白兔：那你们有没有萝卜啊？

** 没有那么聪明的毛驴
   发信人: so (桐叶封晋|恭喜发财~!!), 信区: Joke
   标  题: 没有那么聪明的毛驴
   发信站: 北邮人论坛 (Mon Jul  2 16:11:54 2007), 站内

   一个聪明人在乡下散步，看到磨房里面一头毛驴在拉磨，脖子上头挂着一串铃铛。于是聪明人向磨房主道：
   '你为何要在毛驴的脖子上挂一串铃铛呢？'
   磨房主回答：'我打瞌睡的时候，毛驴常常会偷懒，挂上铃铛以后，如果铃铛不响了，
   我就知道这个畜生又在偷懒了。'
   聪明人想了一下，又问：'如果毛驴停在原地不动，只是摇头，你又能听到铃声，它又没有干活，那怎么办呢？'
   磨房主楞了一下，说：'先生，我哪能买到像您这样聪明的毛驴啊！'

** 找兔子
   测试美国, 香港, 中国大陆三地警察的实力, 联合国将三只兔子放在三个森林中, 看三地警察谁先找出兔子.
   任务:找出兔子

   第一个进森林的是美国警察, 他们先花整整半天时间开会制定作战计划, 严格分工, 然后
   派特种部队快速进入森林进行地毯式搜索,结果开会耽搁了时间, 兔子跑了, 任务失败!!!!

   然后轮到香港警察, 他们派了一百多 号人和几十辆警车在身临其境外一字排开, 由带头
   人 用喇叭喊话:"兔子,兔子,你已经被包围了, 快出来投降......" 半天过去了, 没动静.
   飞 虎队进入森林, 搜索一遍,没结果, 任务失败!!!!

   最后是中国警察, 只有四个, 先打了一天麻将, 黄昏时一人拿 一警棍进入森林,没五分钟,
   听到森林里传来一阵动物的惨叫, 中国警察一人抽着一根烟有说有笑的出来, 后面拖着一
   只鼻青脸肿的熊, 熊奄奄一息的说到:"不要再打了,我就是兔子......."
** 追车
   早上赶公共汽车,到站台的时候,汽车已经启动了。
   于是我只好边追边喊：'师傅,等等我！师傅,等等我呀！'
   这时一乘客从车窗探出头来冲我说了一句：'八戒你就别追了'
** 假钞
   有两个造假钞的不小心造出面值15元的假钞，两人决定拿到偏远山区花掉，当他们拿一张
   15元买了1元的糖葫芦后，他们哭了，农民找了他们两张7块的
** 考试默写
   发信人: teneo (keep walking), 信区: Joke
   标  题: zz考试默写
   发信站: 水木社区 (Tue Sep  9 12:58:30 2008), 站内

   高考了，高考完后又是中考...考题千奇百怪，答卷也五花八门。真佩服现在的学生

   啊，思维跳脱，天马行空，和我们那时候的循规蹈矩，差别太大了，呵呵。看一组语文
   试卷中的填空题―

   1.___，为伊消得人憔悴

   同学答：宽衣解带终不悔

   （正解为“衣带渐宽终不悔”，偶承认这个是思想有问题）

   2.问渠哪得清如许，____

   同学答：心中自有清泉在

   （正解为“唯有源头活水来”，咱还是和水粘了点边~~~）

   3.何当共剪西窗烛，____

   同学答：夫妻对坐到天明

   （语文老师阅卷时笑晕。后在课堂时说此事，又晕！正解为“却话巴山夜雨时”）

   4.蚍蜉撼大树，____

   同学答：一动也不动

   （正解为“可笑不自量”。一动也不动，赫赫，很符合事实阿）

   5.君子成人之美，____

   同学答：小人夺人所爱

   （直接晕死）

   6.穷则独善其身，____

   同学答：富则妻妾成群

   （正解：达则兼济天下）

   7.___，天下谁人不识君

   同学答：只要貌似萨达姆

   （汗|||....）

   8.后宫佳丽三千人，____

   同学答：铁棒也会磨成针~~~（估计不是磨成针这么简单了吧）

   （正解为“三千宠爱在一身”）

   9.身无彩凤双飞翼，___

   同学答：拔毛凤凰不如鸡

   还有个同学答：夫妻双双把家还

   （正解为“心有灵犀一点通”）

   10.东边日出西边雨，___

   同学答：床头打架床尾合

   还有个同学答：上错花轿嫁对郎

   11.__，糟糠之妻不下堂

   同学答：结发之夫不上床

   （语文老师暴怒！）

   12.但愿人长久，____

   同学答：一颗永流传

   （当时狂笑，现在觉得挺经典的。正解为“千里共婵娟”）

   13.西塞山前白鹭飞，___

   同学答：东村河边爬乌龟

   （对的挺工整的）

   14.我劝天公重抖擞，____

   同学答：天公对我吼三吼

   （正解为“不拘一格降人才”，龚自珍）

   15.天生我才必有用，____

   同学答：关键时刻显神通

   又有同学答：老鼠儿子会打洞

   （整办公室的语文老师集体毫无形象的狂笑）

   16.天若有情天亦老，___

   同学答：人不风流枉少年！

   （正解为“月若无恨月长圆” 李贺《金铜仙人辞汉歌》 )（还有一句是“人间正道是沧
   桑”）

   17.洛阳亲友如相问，____

   同学答：请你不要告诉他

   （正解为“一片冰心在玉壶”）

   18.期末考试出对联, 上联是英雄宝刀未老

   该初三同学对下联为：老娘丰韵尤存

   19.良药苦口利于病，___

   同学答：不吃才是大傻瓜

   人生自古谁无死，___

   同学答：只是死的有先后

   （结局：家长会后被老师留下来训话鸟…)

   20.床前明月光，___

   同学答：李白睡的香

   21.管中窥豹，___

   同学答：吓我一跳

   （哈哈哈！正解为“可见一斑”)

   22.___，飞入寻常百姓家

   同学答：康佳彩霸电视机

   23.葡萄美酒夜光杯，___

   同学答：金钱美人一大堆

   24.____，路上行人欲断魂

   初一学生的杰作：半夜三更鬼敲门

   25.还有次考陶渊明的“吾不能为五斗米折腰”，同学填的是“给我六斗就可以”…

   26.老吾老以及人之老，___

   同学答：妻吾妻以及人之妻

   （老师后来评卷时说那个同学特别具有奉献精神，哈哈）

   27.想当年，金戈铁马，___

   同学答：看今朝，死缠烂打

   （正解为“气吞万里如虎”）

   28.五年级的一次考试就考到了“三个臭皮匠，___”

   同学答：臭味都一样

   （把监考和外面的校长笑翻了）

   29.初一的学生对对子，“登城白云间揽山色入怀，___”

   同学答：我到酒店去抱小姐上床

   （他的语文老师差点当场吐血而亡）

   30.两情若是长久时，__

   同学答：该是两人成婚时

   31.沉舟侧畔千帆过，___

   同学答：孔雀开屏花样多

   32.书到用时方恨少，____

   同学答：钱到月底不够花

   33.天若有情天亦老，____

   同学答：人若有情死得早

   （正解为“月若无恨月长圆”）

   34.人生自古谁无死，___

   同学答：有谁大便不带纸

   （没有语言了...）

   35.有次考李清照的如梦令，“知否？知否？___”

   同学答：SORRY I，DONT KNOW...

   （正解为“应是绿肥红瘦”）

   36.有次考鲁迅先生某句：“___，我以我血溅轩辕”

   同学答：他以他刀插我身

   37.语文考试，填空里有一首革命诗：“为人进出的门紧锁着，__

   ，一个声音高喊着：__我渴望自由，但人的身躯怎能从狗洞子里爬出

   …”

   同学答：为狗爬出的洞也锁着 / 他妈的，都锁着！

   38.千山万水总是情，__

   同学答：多给一份行不行

   （批卷老师对了一句：情是情，分是分，多给一份都不行）

   39.高一的时候，一次月考，上句“仰天大笑出门去，（正解）我辈岂是蓬蒿人”。班

   上有人写：一不小心扭到腰。 还有一句，上句：“清水出芙蓉，（正解）天然去雕饰”


   。有人写，淤泥出莲藕；还有人更绝，写：乱世出英雄

   40. 问君能有几多愁，___

       同学答：恰似一壶二锅头

** 从二十楼掉下来和二楼的区别
   发信人: zhuang5122 (管他三九27-闷锅王), 信区: Joke
   标  题: 从二十楼掉下来和二楼的区别。。爆冷
   发信站: 北邮人论坛 (Tue Oct 28 20:42:11 2008), 站内

   二十楼: 啊啊啊啊啊啊啊啊啊啊啊啊~~~~~~~~~~~~~~~~~~~~~~啪~~~
   二 楼: 啪~~~~啊啊啊啊啊啊啊啊啊啊啊啊~~~~~~~~~~~~~~~~~~~~~

   --
   [b]  [url=http://www.xiayy.com]2008年最新冷笑话[/url][/b]
   ※ 来源:·北邮人论坛 http://forum.byr.edu.cn·[FROM: 59.57.167.*]
** 一句话笑话
   - 俺村就剩俺一个光棍儿了，其它男人生了孩儿都结扎了，大夫，您也给俺结扎了吧，我怕
     要是哪个女的怀孕了，这个责任俺担当不起啊。
   - 抢匪：快把保险箱密码说出来！不说杀了你！女职员：杀了我也不说！你糟蹋了我我也不
     说！抢匪上下打量她后：你想得美！
   - 一神经病在床上唱歌,唱着唱着翻了个身,趴在枕头上继续唱歌,主治医生问:“唱就唱吧,
     你翻身干什么?”神经病说:“傻B,A面唱完了当然要唱B面了。”
   - 餐厅中，女：你到底打算跟我结婚吗？男的沉默。女：别以为没人要我，搞火了我马上就
     在这找个人嫁了！侍应生走过来：小姐你把本店的客人都吓跑了。
   - 强盗：“抢劫，都他妈给我趴下！”当他看到一女士的趴下姿势后吼道：“你他妈给我文
     明点，老子只劫财不劫色！”
   - 一位白人到黑人区发表竞选演说，为了赢得黑人选民的支持，演说中他竟脱口而出：“虽
     然我的皮肤是白的，但心却和你们一样黑。”
   - 某男,妻经常红杏出墙,而视若不见,同事送一付对联,上联:只要日子过的去，下联:哪怕头
     上有点绿, 横批:忍者神龟
   - 男女朋友睡一个房间，女的划了条线：过线的是禽兽。醒来发现男的真的没过线，女的狠
     狠打了男的一耳光：你连禽兽都不如！

** 我就胖了,就爱吃肉了怎么了? 老子花了几千万年进化到食物链顶端不是为了吃蔬菜!
** 我刚刚拒绝了levi's美女售货员的求合体的想法
   之前朋友说levi's的牛仔裤很不错，于是我决定去买一条。到了商场逛了逛，走进了levi's的店面。大牌店真不错，售货员都是美女，站成一排一个赛一个清纯漂亮。
   一进店，就有一个很漂亮的售货员跑了过来。“先生，你好。能忙您做点什么么？”
   “把你们最新款裤子拿给我。”
   售货员匆忙拿来一条506跑了过来。为了装作熟客，我接过裤子没搭理她直接走进了试衣间，没想到美女售货员却主动跟上来站在试衣间门口。
   为了防止她偷窥我，我赶紧把试衣间的门关严。然后开始换裤子，我刚把裤子脱了，就听到美女就站在试衣间门口小声的问我：“帅哥，合不合体，合不合体？”
   公共场合她问这种问题，真不害臊。感叹社会风气实在太不好了，日风正下、世态炎凉啊。她问的我可是觉得又害羞又尴尬，不过作为一个品德高尚，有情操的人，我只好用沉默来拒绝她与我合体的要求。
   可没想到的是等我出试衣间，她仍然不依不饶的问，“合体的话，第一次我可以给你打9折哦。”
   我冷峻的走出了试衣间，把裤子拿给了她，我真是对这个美女失望透了。她怎么能把我当成那种爱占小便宜的人呢。虽然她很漂亮而且还是第一次，但是我绝对不能为了9折出卖自己的肉体，虽然那条裤子穿在我身上绝对帅气潇洒，但我还是决定不买了，当然，钱没带够也是另外一方面。我没好意思直接把我高尚的人格说出来，只好对她说“对不起，我不喜欢这裤子。”
   她却“不买没关系，欢迎下次再来哦。”我实在忍无可忍，临出门前我告诉她，“我不是一个随便的人。”只见她窘迫又充满敬仰的神情望着我，红着的脸映红了我胸前的红领巾。我希望经过这次教训她能懂一些做人的道理，虽然裤子没买成，但很开心做了一件好事，于是我笑着离开了。
   以后再不听朋友的买levi's了
** 死猪是检验开水的唯一标准 
[2012-10-19 Fri 13:10]
** cat sleep style                                                  :ATTACH:
:PROPERTIES:
:Attachments: cat_sleep.jpg
:ID:       e6a82ba7-b39e-43d6-8ed1-f629c576de4b
:END:
 
[2012-10-19 Fri 13:47]
** 浣熊                                                             :ATTACH:
:PROPERTIES:
:Attachments: a8e9a317jw1dwdhasb1mij.jpg
:ID:       8b22d46f-3ee5-4a02-8a22-a523248048f1
:END:
 
[2012-10-19 Fri 13:51]
