(add-to-list 'load-path "~/.elisp/color-theme-6.6.0/")
(add-to-list 'load-path "~/.elisp/themes/")
;; allow for color prompt in shell
(ansi-color-for-comint-mode-on)
;; (set-face-foreground 'font-lock-comment-face "#95917E")
;; (set-face-foreground 'font-lock-comment-face "gold")
;; (set-face-foreground 'font-lock-string-face "#61ce3c")
;; (set-face-foreground 'font-lock-keyword-face "#f8dd2d")
;; (set-face-foreground 'font-lock-function-name-face "#e3611f")
;; (set-face-foreground 'font-lock-variable-name-face "#98fbff")
;; (set-face-foreground 'font-lock-type-face "#A6E22E")
;; (set-face-foreground 'region "#272822")
;; (set-face-background 'region "#66D9EF")
;; (set-face-foreground 'font-lock-constant-face "#66d9ef")
;; (set-background-color "#0b0f23")
;; (set-foreground-color "#f8f8f2")
;; (setq-default cursor-type 'box)
;; (set-cursor-color "red")

(require 'color-theme)
(require 'color-theme-solarized)
(color-theme-solarized-dark)
