(if (string= window-system "w32")
    (progn 
      (setq browse-url-browser-function (quote browse-url-default-windows-browser))
      (add-hook  'window-setup-hook ' (lambda ()
					(interactive)
					(w32-send-sys-command #xf030)
					) )
      (prefer-coding-system 'gb18030)
      )
  )
