(if (executable-find "w3m")
    (progn
      (add-to-list 'load-path "~/.elisp/emacs-w3m/")
      (require 'w3m)
      (setq w3m-use-cookies t)
      (setq w3m-use-form t)
      (setq w3m-tab-width 8)
      (setq w3m-use-cookies t)
      (setq w3m-use-toolbar t)
      (setq w3m-use-mule-ucs t)
      (setq w3m-fill-column 120)
      (setq w3m-default-display-inline-image t)
      (setq w3m-default-toggle-inline-images t)
      (setq w3m-home-page "http://www.gogole.com")
      (setq browse-url-browser-function 'w3m-browse-url)
      (setq w3m-view-this-url-new-session-in-background t)
      (setq w3m-command-arguments
	    (nconc w3m-command-arguments
		   '("-o" "http_proxy=http://build_server:3128")))
      )
  )
